### ISSUE TITLE
What does 'decide to not show expired entries' mean?

### ISSUE THREAD

**Issue by rangerxusa** [Rookiestyle/NotesFontSelector#1]
Your overview states:
If you want a different font for notes and do not want to change this in windows, this plugin is for you. You can also decide to not show expired entries at all.

Can you explain what you mean by 'You can also decide to not show expired entries at all.' Not sure what this is supposed to do.  I don't see an option for turning this on or off.. Is this something not implemented or is automatic? Is there an option switch somewhere? I don't see how to test this feature assuming it is active. since I don't know what it is doing.

The font selection for Notes works great. Thanks much! No problem with selecting a Note font,  I did modify your code to remove the tab for turning on/off debugging for this plugin as this seemed more for designing/programming the plugin than what I as a user need. It also removed an unnecessary tab from the Keepass Options window since only your plugin was listed in that tab..

Thanks!

**Comment by Rookiestyle** [comment]
This is a copy & paste error from another plugin - [KPColorChange](https://github.com/Rookiestyle/KPColorChange). 
I'll update the readme

**Comment by rangerxusa** [comment]
Ok. That explains it.
Thanks again for the great plugin NotesFontSelector.
